### ISSUE TITLE
Keyboard hang when using space cadet with rollover or LT(LOWER,KC_SPC)

### ISSUE THREAD

**Issue by Lenbok** [qmk/qmk_firmware#3233]
I have a couple of Redox keyboards I've built (I believe that the core keyboard code is essentially the same as Lets Split). The two halves are connected using I2C.

When I enabled space cadet shift in my keymap, I found that pressing one shift then the other would crash the keyboard. In that case I found that:
````
#define DISABLE_SPACE_CADET_ROLLOVER
````
made the problem go away. But it seems like a bug - the define should only be needed if you want to change the rollover behaviour rather than preventing hangs.

Then just today I tried making my RAISE / LOWER keys have dual function and encountered a similar problem. Tapping the key has the expected behaviour, but pressing the key in conjunction with another one (in my case I was pressing '5' in order to get an 'F5' in my keymap) caused the keyboard to hang.

I am *guessing* that these are related problems, but I could be wrong.

My keymap is at: https://github.com/Lenbok/qmk_firmware/blob/master/keyboards/redox/keymaps/lenbok/keymap.c

**Comment by drashna** [comment]
:D

Add `COMMAND_ENABLE = no` to your rules.mk file, and recompile. That should fix the issue. 
https://docs.qmk.fm/#/feature_command?id=configuration

**Comment by Lenbok** [comment]
@drashna That does fix the space cadet behaviour, but I still get the hang using ```LT(LOWER,KC_SPC)``` and ```LT(RAISE,KC_ENT)``` - any ideas about them?

**Comment by Lenbok** [comment]
Hmmm, using ```LT(_LOWER,KC_SPC)``` and ```LT(_RAISE,KC_ENT)``` does work though. I guess this another case of knowing how to tickle the firmware the right way?

It would be nice if qmk had some kind of validation routines to detect or prevent non-working combinations like this and the space cadet situation.

**Comment by Lenbok** [comment]
@drashna Just an idea - in the Marlin 3d printer firmware, they have many sanity checks that get evaluated to help catch some of the possible invalid configurations. See  https://github.com/MarlinFirmware/Marlin/blob/ac3fab7a9680a880fd1b113be7e758c6dabb2a57/Marlin/SanityCheck.h

Maybe something like that would be useful here? (I realise it won't get all the situations though).

**Comment by drashna** [comment]
The problem with that, is that most of the file is looking at defines and the like.  Which isn't what happens here. 

Most of the error checking is handled by avr-gcc right now, so ... we'd need to implement some sort of script to do this, I think.  And that's super complicated.
