### ISSUE TITLE
Rotary Encoder not working with Pro Micro

### ISSUE THREAD

**Issue by BenRoe** [qmk/qmk_firmware#4627]
I try to get the encoder working on a breadboard with a Pro Micro. Added the code from [feature_encoders.md](https://beta.docs.qmk.fm/features/feature_encoders) and use the Pins PD1 (2) & PD4 (4).

![](https://github.com/and3rson/qmk_firmware/raw/master/keyboards/lets_split/keymaps/anderson/encoder.png)

**Describe the bug**

The key is not triggered if i rotate the encoder.

**System Information**
 - Keyboard:  Breadboard
   - Revision (if applicable):  
 - Operating System: Windows 10

Full code 
https://github.com/BenRoe/qmk_firmware/tree/breadboard-test/keyboards/breadboard

If i use the code from https://github.com/and3rson/qmk_firmware/tree/master/keyboards/lets_split/keymaps/anderson
Everything works.

**Comment by nooges** [comment]
I ran into the same issue with 32u4, if I change the lines in encoder.c involving `readPin()` by casting to bool as follows, the encoder works:

Old: `(readPin(encoders_pad_a[i]) << 0) | (readPin(encoders_pad_b[i]) << 1)`

New: `((bool)readPin(encoders_pad_a[i]) << 0) | ((bool)readPin(encoders_pad_b[i]) << 1)`

**Comment by nooges** [comment]
Should be fixed now that https://github.com/qmk/qmk_firmware/pull/4681 has been merged in.

**Comment by BenRoe** [comment]
Tried it today, but still not working.

**Comment by LouWii** [comment]
This bug is still present. I'm using a ProMicro and an encoder on pins D2 and D3.

The detection was really messy. Either the firmware was "detecting" multiple change per second. Or none. Depending on the encoder position.

After using @nooges fix, the encoder behaves properly.
