### ISSUE TITLE
Keyboard does not register keys that are held down during power-up

### ISSUE THREAD

**Issue by jordiorlando** [qmk/qmk_firmware#611]
I run several OSes on my machine and I need to press F11 or DEL during boot to access the boot menu or BIOS. If I power on my computer and immediately hold down any key, it won't actually register unless I press it again after the keyboard has turned on, so it's difficult to time it right so that the motherboard actually recognizes it. Could the default behavior be changed so that any keys are recognized immediately upon the firmware finishing its initialization? I took a quick look and it seems the answer may lie somewhere within matrix_init().

**Comment by jackhumbert** [comment]
Ah, that's an interesting issue - do you have bootmagic off? That may be interfering with that. If it still doesn't work, this is definitely something I'd want to add (at least as an option).

**Comment by 0xdec** [comment]
Yeah, bootmagic is disabled.

**Comment by drashna** [comment]
Is this still an issue? 

Also, yeah, adding this to your keymap.c may help:
```
void matrix_init_user(void) {
  register_code(KC_F11);
  wait_ms(3000);
  unregister_code(KC_F11); 
}
```

This should work and hold F11 down for the first 3 seconds of powering on.

**Comment by 0xdec** [comment]
This is still an issue as of 298ac18

**Comment by adiabatic** [comment]
Still an issue, as is #1149 (probably the same issue).

**Comment by fredizzimo** [comment]
After a very quick lock, I think this is the offender https://github.com/qmk/qmk_firmware/blob/master/tmk_core/protocol/lufa/lufa.c#L555

Try to comment that out, and see if it works better.

**Comment by AGausmann** [comment]
I'm having a similar problem, I'm unable to use any QMK keyboard during the boot process, including the GRUB boot menu.

**Comment by drashna** [comment]
@AGausmann have you tried commenting out the relevant like of code?

**Comment by dylancopeland** [comment]
I am also running into this same issue. Has this been resolved in a recent firmware release?

For those also with this issue, if your keyboard has a backlight, enable it and wait for it to be illuminated before pressing the key. I've been doing that to resolve the timing issues.

**Comment by aaahrens** [comment]
i am also getting this issue, any updates?

**Comment by thealpa** [comment]
Still an issue as of https://github.com/qmk/qmk_firmware/commit/bd1c048a76e0ba84513caf1d59573dc55618c99a, I tried commenting out `clear_keyboard();` from https://github.com/qmk/qmk_firmware/blob/master/tmk_core/protocol/lufa/lufa.c#L623 but this doesn't resolve the issue for me.

**Comment by tzarc** [comment]
Closing due to inactivity.

**Comment by awilkins** [comment]
Arrived here after discovering my Keychron Q6 doesn't work in GRUB, which means I have to plug in another keyboard to change boot options.

From reading the source, the firmware for this one uses `CUSTOM_MATRIX = lite` ... I don't know when this keyboard is "properly" initialized.

**Comment by awilkins** [comment]
I found that upgrading my Q6 to the latest release firmware from Keychron fixed my boot-time issues.
